language: node_js
node_js: 8.11.0
script: npm run build
deploy:
  provider: s3
  bucket: recipes-web-storage
  skip_cleanup: true
  access_key_id:
    secure: ww7hnfoO+Rp5Th1MIxNT3wpvVzhKo3vh+FiELm44moBT+R7RoYQfjxGZSwkJExrYVVl3qknzBRWDIGfUVexVK0hmUnqd8/WEk3piqLG08Q1UssdbthMA4nEWukuJdABvkfmEjLixlXdHYITeUZ5YF8cUdICf4dwgnCn5fQaw98IZm9rl2xxUQfcd9j6O6NKlqJPkFKVEUUNNnsJBqvkBSRuZl3aR6FqrNuaipvRS7iSYJsFJAStLqtxStq0o8wGb4NqqJ5izEXAD3MvOezNxAC3L4DX4HYmhze3lD6POcCLNuimiCIiX7l9BH+9uPTA0wjwF77dkuPQmXOnr0Rj6tyV8qhsRAVkXS0EHg/zOzntN0GRS2LRPem+dX3V4/WaNPkZFwYloLTQHvCHF5XQvfyuACHS8LOi0WYpwIPgxB63BhPEk+/F2BBHImUDxiDfnFlgCK6CG4Z9WrDQWQmWurZDeIpIe32R2Cb5u2SWoEaWAIMbwR2cd5uofdomg2CEfvhKdMpAU/nJL9Rxwtquh337DYFdvDiyZQ3ThcosdmkVFtw4W+OlKk3HVUpJVyWB0v7Zbwqqt+Q98uguE6AcqbMw9B2sQUFNvc+gspidQOYAPMz2RmSj6VMzByA/V4kkUK8abj14kzWyAeHtSldakqvmqIEPOCA3oCEnKd1/YI/I=
  secret_access_key:
    secure: gwoX4098UO+5MEjKz2sMwplCRa2AhiLkegCHu9Pn+a/6EB/Xn2NLtBfVVR6aaLlPx65UT+U8izy+E/euhvRTOKWNuaz2VjSBF96KqR9e0jtJEkyYlbQxIbtXfpspVEeLfzkt2JPZLAwRsLMNeDvWU5vshExzc6xZtPCxp7SRc+hefDni2vc+WlonBaefsRtaQ+bY89WDLCIfo1pskR7AZ629CU85BpPlrI+nJ6Bn8q1dyYKoe2+lguvDqQ5B+fXcTQ59r6Wn4Bb7PLwY+5fbBmsPd0ZFzgUvNDIoaBVGIBGJlstRFum8bhjlD95DkEV/teMjwfd61aGOX/pfIXgnrhhYn9zUubcnAtWW2pfiJ7LBnJiT41CDfam1THuxTFpgMefEdQec5NglMhJIF/JVzA3yESGseljJR1aiJbIl3aBabZaOWgq+9TxI1G/+wDKmEXn49Hu9ebEI3aHGzcx2XBF/wxY+GL4cuIa8/ZXeT6iw/acYw+23Yjzv8WmnivdsDV9zdqV6jUZyjoTxZ4tC9ypCIzw/fdt36R6Js1xuQOwJXFT2s+6zkddrbcxU9KqaMcIa0GnRQcMr3NwbzjHB3uHO8p09ijB9+EwrATC3abAHBoVBcfFYzhLRA3aCAA/Zi3jhdfc7pgt7Bsg+u9d9G3NlZiHL6JIvgMxnTxhPoqk=
  upload_dir: "stage"
  local_dir: "build"
  on:
    branch: deploy-settings